Set TOOLCHAIN to bikeshed
Since the top-level has an index.html file, ReSpec
is assumed by default rather than bikesed:

```
Generate Static HTML
  Converting ReSpec document 'index.html' to HTML...
  $ respec -s "index.html" -o "index.html.built.html" --verbose --timeout 20
  [Timeout: 20000ms] Launching browser
  [Timeout: 14181ms] Navigating to file:///home/runner/work/ngff/ngff/index.html
  [Timeout: 13906ms] Navigation complete.
  Error: 🕵️‍♀️  That doesn't seem to be a ReSpec document. Please check manually: file:///home/runner/work/ngff/ngff/index.html
      at checkIfReSpec (/home/runner/.config/yarn/global/node_modules/respec/tools/respecDocWriter.js:178:11)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async toHTML (/home/runner/.config/yarn/global/node_modules/respec/tools/respecDocWriter.js:82:5)
      at async run (/home/runner/.config/yarn/global/node_modules/respec/tools/respec2html.js:137:40)
```